import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container h-full mx-auto">
          <div className="flex flex-row gap-3 p-2 rounded-sm bg-blue-600 text-white">
            <Link href="/" className="underline">
              Home page
            </Link>
            <Link href="/login" className="underline">
              Login
            </Link>
          </div>
          <div className="">{children}</div>
          <div className="">{auth}</div>
          <div className="">Footer</div>
        </div>
      </body>
    </html>
  );
}
